### PR TITLE
Prevent Ghosting

### PR DESCRIPTION
**Pull request by MrUnknownGamer**
Prevents ghosting.

Ex. If an innocent dies and they have a report, it will say that are responding to their reports, but they have not been ID, thus people can just mark the dead because they saw the message in chat.

This prevents that from happening,

### CODE REVIEW

**Comment by Tommy228** [comment]
There's already a check for that and you removed it.

https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/cl_rdm_manager.lua#L346

**Comment by MrUnknownGamer** [comment]
I still see the message when I'm sliver, which causes ghosting

**Comment by MrUnknownGamer** [comment]
Alive*

**Comment by MrUnknownGamer** [comment]
Do you want me to keep the .IsActive and just add and/or with my code?

**Pull request closed without merging**
