### PR TITLE
Stop SQL Error "no such column: steamid"

### PR DESCRIPTION
**Pull request by GGG-KILLER**
Code I use to test for SQL errors:
```lua
local sqlQuery = sql.Query
local errs = {}
function _G.sql.Query( str )
	local ret = sqlQuery( str )
	local err = sql.LastError()
	if err and not errs[err] then
		local err = sql.LastError()
		MsgC(Color(241, 196, 15), "Error on SQL Query: " .. str .. "\n")
		MsgC(Color(241, 196, 15), "Error message: " .. err .. "\n")
		debug.Trace()
		errs[err] = true
	end
	return ret
end
```

### CODE REVIEW

**Comment by zerfgog** [comment]
Don't override sql.Query. It will make the function much slower for little benefit.

**Comment by GGG-KILLER** [comment]
Common practice since I got some errors ( infinite loops) when I overwrote other functions before.
And this code should be used only when testing, it MUST be removed after testing period is over.

**Comment by zerfgog** [comment]
Whenever you access a global function you implicitly index _G.

**Comment by GGG-KILLER** [comment]
We're derailing the objective of the pull request here, I suggest we discuss this over steam if you want.

**Pull request merged**
