### PR TITLE
Web Fixes

### PR DESCRIPTION
**Pull request by comedinha**

### CODE REVIEW

**Comment by comedinha** [comment]
http://sotserv.com/dmglog

**Comment by Tommy228** [comment]
yo thanks

**Comment by Linkfan123** [comment]
Web _Fixes_? Looks more like a Web _Integration_ from all the new code you added.  :smile: 
A big thumbs up :+1:

**Comment by Tommy228** [comment]
Sorry for reverting but it was conflicting with the dev branch, can you create a PR again?

**Pull request merged**
