### PR TITLE
Compatibility with TTT2 and Code Cleanings

### PR DESCRIPTION
**Pull request by Alf21**
- Compatibility with TTT2 (https://steamcommunity.com/sharedfiles/filedetails/?id=1357204556)
- code cleaning (like https://en.wikipedia.org/wiki/Coding_conventions)

### CODE REVIEW

**Comment by Alf21** [comment]
I would recommend testing this before you merge it. I did a lot of changes.

**Comment by MinIsMin** [comment]
Something is very off with your PR.
I think you made your changes on top of an old version instead of master.
Two examples:
[config/config.lua](https://github.com/Tommy228/tttdamagelogs/pull/361/files#diff-a861a5b4823783e6fb196e23ce9b4845L109): Why remove the (working) discord settings?
[server/autoslay.lua](https://github.com/Tommy228/tttdamagelogs/pull/361/files#diff-46e03d2c2573954c5f1d4a5f19f4758bL5): Why remove a needed `util.AddNetworkString`?
Nearly all recent commit changes are missing.


I am always grateful for helpful PRs but with 48 changed files it is very confusing.

If possible, can you split the PR (e.g. one for code cleaning, another for TTT2 compatibility) and state the changes you made?

**Comment by Alf21** [comment]
Sure, that will be a better solution. I will recreate a PullRequest

**Comment by Alf21** [comment]
Fixed the name issue. Tested on my own. In addition to that, I did some changes. Please give a look at it.

**Comment by Tommy228** [comment]
Yup, I'll test it and merge it this WE

**Comment by Tommy228** [comment]
Tested it, should be good. Thanks.

**Pull request merged**
