### PR TITLE
optimization

### PR DESCRIPTION
**Pull request by Heyter**

### CODE REVIEW

**Comment by CSchulz** [comment]
Would it not be better to use `for i,x do` instead of `ipairs`?

https://springrts.com/wiki/Lua_Performance#TEST_9:_for-loops

**Comment by Tommy228** [comment]
Using standard `for i,x do` loops would make the code harder to read. I really don't think these optimizations are necessary but it doesn't hurt anyone. Also you have fixed a few non-translated strings. Thanks for the work.

**Comment by Heyter** [comment]
@CSchulz special for u.
http://i.imgur.com/epbrstM.png?1
8 milliseconds -_-

**Comment by CSchulz** [comment]
Thank you, but I think even such small optimization are good for improving all the stuff. 😄

**Comment by Heyter** [comment]
@CSchulz, Then you are a bad coder.

**Comment by CSchulz** [comment]
I am talking about all in all, not a single place. :) 

When you have multiple places loosing some time, it will sum up some day.

**Comment by Heyter** [comment]
@CSchulz , Do it yourself :smiley:

**Pull request merged**
