### PR TITLE
Discord webhooks

### PR DESCRIPTION
**Pull request by iagrib**
Implemented discord webhooks support.

Tested on local server, will test this version on my server later today (right now it has a simple `http.Post` that posts a short message).

Here's how it looks:

What should I improve/change?

*P.S. Seems like I messed something up with my fork. I don't know why older commits are displayed as part of this PR. It doesn't seem to have any effect on actual changes anyway.*

### CODE REVIEW

**Comment by yupi2** [comment]
The clients will be sent the config.lua file too which will include the webhook+token url. Could maybe set the url in a convar instead.

**Comment by iagrib** [comment]
I actually didn't think about it, very stupid of me.

Thanks for reminding about this.

**Comment by yupi2** [comment]
I can relate. I tried to get a thing merged into ULX that would allow you to click on workshop addon links and open in the Steam overlay but that required the HTML panel to run Lua... and the motd file is stored clientside so I almost got clientside Lua execution in ULX...

**Comment by iagrib** [comment]
Noticed a little inconsistency with convar names: every convar looks like `ttt_dmglog`**`s`**`_...`, but language one is `ttt_dmglog_language`. Which format should I follow for this PR?

**Comment by iagrib** [comment]
Thanks!

Edited the convar name.

**Pull request merged**
