### PR TITLE
Fix double space

### PR DESCRIPTION
**Pull request by UnacceptableUse**

### CODE REVIEW

**Comment by EstevanTH** [comment]
Very nice! :heart:

**Comment by MinIsMin** [comment]
There is a rewritten version of TTTDamagelogs where this and many other bugs are fixed.
The problem is that this fixed version still has some errors and we can not publish it like this.
At the moment, we don't have the time to fix them, but this will change in the future.

Currently, I can only say that it still takes some time.

**Comment by CSchulz** [comment]
Is there any possiblity to support you? Access to private repository and so on? Tommy has me on Steam, just write me.

**Comment by MinIsMin** [comment]
If you want, you can view the project and post suggestions for improvement, or just say something looks good or not: https://github.com/MinIsMin/NotYetTDM/tree/MyDimeIsUp

**Comment by MinIsMin** [comment]
@CSchulz What's your Steam name? (Will remove this comment after you told me)

**Comment by CSchulz** [comment]
H3llGhost                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Von: MinGesendet: Freitag, 10. März 2017 15:35An: Tommy228/TTTDamagelogsAntwort an: Tommy228/TTTDamagelogsCc: CSchulz; MentionBetreff: Re: [Tommy228/TTTDamagelogs] Fix double space (#256)@CSchulz What's your Steam name? (Will remove this comment after you told me)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Tommy228/TTTDamagelogs","title":"Tommy228/TTTDamagelogs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Tommy228/TTTDamagelogs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MinIsMin in #256: @CSchulz What's your Steam name? (Will remove this comment after you told me)"}],"action":{"name":"View Pull Request","url":"https://github.com/Tommy228/TTTDamagelogs/pull/256#issuecomment-285684029"}}}

**Pull request closed without merging**
