### PR TITLE
Make report status labels updade their colors immediately after status is changed

### PR DESCRIPTION
**Pull request by iagrib**
Like it used to be before 3.0.0. There might be a better/cleaner way to do this though.

Also removed `testp` command as I'm pretty sure it's not supposed to be here?

### CODE REVIEW

**Comment by MinIsMin** [comment]
Why not removing the duplicate at [tabs/rdm_manager.lua#L438-L455](https://github.com/iagrib/TTTDamagelogs/blob/c7c194d9a46db42e9513104fa9cc7331f1e5dd5e/lua/damagelogs/client/tabs/rdm_manager.lua#L438-L455) since it would be sometimes run twice?

**Comment by iagrib** [comment]
Would it? These seem to be located in different branches of `if...else...end` statement.

**Comment by MinIsMin** [comment]
Sorry, I meant this: https://github.com/MinIsMin/TTTDamagelogs/commit/d540b954b8865819cf3a5adb0a3cb9e9b192da37

**Comment by MinIsMin** [comment]
Sorry, I meant this: https://github.com/MinIsMin/TTTDamagelogs/commit/29b3f5b2d51c3e0b1538fe832cbe4b6a34ce300c

**Comment by iagrib** [comment]
I wanted to do that, but then it would not work if that report is finished and 'hide finished reports' is turned on.

**Comment by MinIsMin** [comment]
Okay, I will look into that.

**Comment by iagrib** [comment]
Can do this, but then additional check is performed at cost of code readability.

**Pull request merged**
